# Generated by Django 5.0 on 2023-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('engine_serial_number', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('pump_type', models.CharField(blank=True, max_length=500, null=True)),
                ('pump_specifications', models.CharField(blank=True, max_length=500, null=True)),
                ('city_of_origin', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(blank=True, max_length=500, null=True)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
