# Generated by Django 5.0 on 2023-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='row',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
