# Generated by Django 5.0 on 2023-12-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_exceldata_engine_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnginKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PumpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('date', models.DateField()),
                ('courier', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_company', to='home.buildercompany')),
                ('destination_city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='home.destinationcity')),
                ('engine_power', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pump', to='home.enginkind')),
                ('origin_city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='home.origincity')),
                ('pump_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pump', to='home.pumpmodel')),
            ],
        ),
    ]
